//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using BizStream.Kentico.Xperience.AspNetCore.Models;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine;

[assembly: RegisterDocumentType( StatusCodeNode.CLASS_NAME, typeof( StatusCodeNode ) )]

namespace BizStream.Kentico.Xperience.AspNetCore.Models
{
    /// <summary>
    /// Represents a content item of type StatusCodeNode.
    /// </summary>
    public partial class StatusCodeNode : TreeNode
    {
        #region "Constants and variables"

        /// <summary>
        /// The name of the data class.
        /// </summary>
        public const string CLASS_NAME = "BizStream.StatusCodeNode";


        /// <summary>
        /// The instance of the class that provides extended API for working with StatusCodeNode fields.
        /// </summary>
        private readonly StatusCodeNodeFields mFields;

        #endregion


        #region "Properties"

        /// <summary>
        /// StatusCodeNodeID.
        /// </summary>
        [DatabaseIDField]
        public int StatusCodeNodeID
        {
            get
            {
                return ValidationHelper.GetInteger( GetValue( "StatusCodeNodeID" ), 0 );
            }
            set
            {
                SetValue( "StatusCodeNodeID", value );
            }
        }


        /// <summary>
        /// Status Code.
        /// </summary>
        [DatabaseField]
        public int HttpStatusCode
        {
            get
            {
                return ValidationHelper.GetInteger( GetValue( "HttpStatusCode" ), 0 );
            }
            set
            {
                SetValue( "HttpStatusCode", value );
            }
        }


        /// <summary>
        /// Content.
        /// </summary>
        [DatabaseField]
        public string Content
        {
            get
            {
                return ValidationHelper.GetString( GetValue( "Content" ), @"" );
            }
            set
            {
                SetValue( "Content", value );
            }
        }


        /// <summary>
        /// Gets an object that provides extended API for working with StatusCodeNode fields.
        /// </summary>
        [RegisterProperty]
        public StatusCodeNodeFields Fields
        {
            get
            {
                return mFields;
            }
        }


        /// <summary>
        /// Provides extended API for working with StatusCodeNode fields.
        /// </summary>
        [RegisterAllProperties]
        public partial class StatusCodeNodeFields : AbstractHierarchicalObject<StatusCodeNodeFields>
        {
            /// <summary>
            /// The content item of type StatusCodeNode that is a target of the extended API.
            /// </summary>
            private readonly StatusCodeNode mInstance;


            /// <summary>
            /// Initializes a new instance of the <see cref="StatusCodeNodeFields" /> class with the specified content item of type StatusCodeNode.
            /// </summary>
            /// <param name="instance">The content item of type StatusCodeNode that is a target of the extended API.</param>
            public StatusCodeNodeFields( StatusCodeNode instance )
            {
                mInstance = instance;
            }


            /// <summary>
            /// StatusCodeNodeID.
            /// </summary>
            public int ID
            {
                get
                {
                    return mInstance.StatusCodeNodeID;
                }
                set
                {
                    mInstance.StatusCodeNodeID = value;
                }
            }


            /// <summary>
            /// Status Code.
            /// </summary>
            public int HttpStatusCode
            {
                get
                {
                    return mInstance.HttpStatusCode;
                }
                set
                {
                    mInstance.HttpStatusCode = value;
                }
            }


            /// <summary>
            /// Content.
            /// </summary>
            public string Content
            {
                get
                {
                    return mInstance.Content;
                }
                set
                {
                    mInstance.Content = value;
                }
            }
        }

        #endregion


        #region "Constructors"

        /// <summary>
        /// Initializes a new instance of the <see cref="StatusCodeNode" /> class.
        /// </summary>
        public StatusCodeNode( ) : base( CLASS_NAME )
        {
            mFields = new StatusCodeNodeFields( this );
        }

        #endregion
    }
}
